version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      development-tooling:
        patterns:
          - "@biomejs/biome"
          - "@types/node"
          - "typescript"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
